version: '3.8'
services:
  build:
    build: .
    container_name: rental-api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - api-network

networks:
  api-network:


    